// <auto-generated />
using System;
using DataContext.MyDbContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataContext.Migrations
{
    [DbContext(typeof(MyContext))]
    partial class MyContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DataContext.Entity.ChiTietCheTao", b =>
                {
                    b.Property<int>("VatTuId")
                        .HasColumnType("int");

                    b.Property<int>("LenhSXId")
                        .HasColumnType("int");

                    b.Property<int?>("DVTinhId")
                        .HasColumnType("int");

                    b.Property<double>("GiaVatTu")
                        .HasColumnType("float");

                    b.Property<int>("SoLuongCan")
                        .HasColumnType("int");

                    b.Property<double>("ThanhTien")
                        .HasColumnType("float");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("VatTuId", "LenhSXId");

                    b.HasIndex("LenhSXId");

                    b.ToTable("ChiTietCheTaos");
                });

            modelBuilder.Entity("DataContext.Entity.ChiTietDonHang", b =>
                {
                    b.Property<int>("SanPhamId")
                        .HasColumnType("int");

                    b.Property<int>("DonHangId")
                        .HasColumnType("int");

                    b.Property<int>("DaLay")
                        .HasColumnType("int");

                    b.Property<double>("DonGia")
                        .HasColumnType("float");

                    b.Property<int?>("DonViTinh")
                        .HasColumnType("int");

                    b.Property<int>("SoLuongHang")
                        .HasColumnType("int");

                    b.Property<double>("ThanhTien")
                        .HasColumnType("float");

                    b.Property<double>("Thue")
                        .HasColumnType("float");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("SanPhamId", "DonHangId");

                    b.HasIndex("DonHangId");

                    b.ToTable("ChiTietDonHang");
                });

            modelBuilder.Entity("DataContext.Entity.ChiTietDonNhap", b =>
                {
                    b.Property<int>("DonNhapId")
                        .HasColumnType("int");

                    b.Property<int>("VatTuId")
                        .HasColumnType("int");

                    b.Property<double>("DonGia")
                        .HasColumnType("float");

                    b.Property<int?>("DonViTinh")
                        .HasColumnType("int");

                    b.Property<int>("SoLuongHang")
                        .HasColumnType("int");

                    b.Property<double>("ThanhTien")
                        .HasColumnType("float");

                    b.Property<double>("Thue")
                        .HasColumnType("float");

                    b.HasKey("DonNhapId", "VatTuId");

                    b.HasIndex("VatTuId");

                    b.ToTable("ChiTietDonNhap");
                });

            modelBuilder.Entity("DataContext.Entity.ChiTietPhieuNhap", b =>
                {
                    b.Property<int>("PhieuNhapId")
                        .HasColumnType("int");

                    b.Property<int>("VatTuId")
                        .HasColumnType("int");

                    b.Property<double>("DonGia")
                        .HasColumnType("float");

                    b.Property<int>("SoLuongHang")
                        .HasColumnType("int");

                    b.Property<double>("ThanhTien")
                        .HasColumnType("float");

                    b.Property<double>("Thue")
                        .HasColumnType("float");

                    b.HasKey("PhieuNhapId", "VatTuId");

                    b.HasIndex("VatTuId");

                    b.ToTable("ChiTietPhieuNhap");
                });

            modelBuilder.Entity("DataContext.Entity.ChiTietPhieuXuat", b =>
                {
                    b.Property<int>("PhieuXuatId")
                        .HasColumnType("int");

                    b.Property<int>("SanPhamId")
                        .HasColumnType("int");

                    b.Property<double>("DonGia")
                        .HasColumnType("float");

                    b.Property<int>("SoLuongHang")
                        .HasColumnType("int");

                    b.Property<double>("ThanhTien")
                        .HasColumnType("float");

                    b.Property<double>("Thue")
                        .HasColumnType("float");

                    b.HasKey("PhieuXuatId", "SanPhamId");

                    b.HasIndex("SanPhamId");

                    b.ToTable("ChiTietPhieuXuat");
                });

            modelBuilder.Entity("DataContext.Entity.DVTinh", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreateBy")
                        .HasColumnType("int");

                    b.Property<double>("HeSo")
                        .HasColumnType("float");

                    b.Property<string>("KyHieu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mota")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenDVi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdateAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UpdateBy")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("DVTinh");
                });

            modelBuilder.Entity("DataContext.Entity.DonHang", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreateBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("HetHan")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("HieuLuc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDonHang")
                        .HasColumnType("bit");

                    b.Property<int>("KhachHangId")
                        .HasColumnType("int");

                    b.Property<int?>("KhoChuaId")
                        .HasColumnType("int");

                    b.Property<string>("MaDH")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("NgayDatHang")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayGiaoHang")
                        .HasColumnType("datetime2");

                    b.Property<int?>("PhuongThucThanhToanId")
                        .HasColumnType("int");

                    b.Property<double>("Thue")
                        .HasColumnType("float");

                    b.Property<double>("TienTruocThue")
                        .HasColumnType("float");

                    b.Property<double>("TongGTriDH")
                        .HasColumnType("float");

                    b.Property<int>("TongHang")
                        .HasColumnType("int");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdateAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UpdateBy")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("KhachHangId");

                    b.HasIndex("MaDH")
                        .IsUnique();

                    b.HasIndex("PhuongThucThanhToanId");

                    b.ToTable("DonHang");
                });

            modelBuilder.Entity("DataContext.Entity.DonNhap", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreateBy")
                        .HasColumnType("int");

                    b.Property<int?>("KhoHangId")
                        .HasColumnType("int");

                    b.Property<int?>("LenhSanXuatId")
                        .HasColumnType("int");

                    b.Property<string>("MaDGH")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("NhaCungCapId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ThoiGianGiao")
                        .HasColumnType("datetime2");

                    b.Property<double>("Thue")
                        .HasColumnType("float");

                    b.Property<double>("TienTruocThue")
                        .HasColumnType("float");

                    b.Property<double>("TongGTriDH")
                        .HasColumnType("float");

                    b.Property<int>("TongHang")
                        .HasColumnType("int");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdateAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UpdateBy")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MaDGH")
                        .IsUnique();

                    b.HasIndex("NhaCungCapId");

                    b.ToTable("DonNhap");
                });

            modelBuilder.Entity("DataContext.Entity.HoaDon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreateBy")
                        .HasColumnType("int");

                    b.Property<int?>("DonHangId")
                        .HasColumnType("int");

                    b.Property<int?>("DonNhapId")
                        .HasColumnType("int");

                    b.Property<string>("MaHD")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("NgayLap")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTra")
                        .HasColumnType("datetime2");

                    b.Property<int?>("PhuongThucThanhToanId")
                        .HasColumnType("int");

                    b.Property<int?>("SoLan")
                        .HasColumnType("int");

                    b.Property<double>("SoTienTra")
                        .HasColumnType("float");

                    b.Property<int>("TinhTrangHoaDon")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdateAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UpdateBy")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MaHD")
                        .IsUnique();

                    b.ToTable("HoaDon");
                });

            modelBuilder.Entity("DataContext.Entity.KhachHang", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreateBy")
                        .HasColumnType("int");

                    b.Property<string>("DiaChi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("HinhAnh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoTenKh")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Sdt")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("UpdateAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UpdateBy")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("KhachHang");
                });

            modelBuilder.Entity("DataContext.Entity.KhoChua", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreateBy")
                        .HasColumnType("int");

                    b.Property<string>("DiaChiKho")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenKho")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("UpdateAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UpdateBy")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("KhoChua");
                });

            modelBuilder.Entity("DataContext.Entity.KhoSanPham", b =>
                {
                    b.Property<int>("SanPhamId")
                        .HasColumnType("int");

                    b.Property<int>("KhoChuaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayHetHan")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgaySX")
                        .HasColumnType("datetime2");

                    b.Property<string>("SoLo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SoLuongTon")
                        .HasColumnType("int");

                    b.HasKey("SanPhamId", "KhoChuaId");

                    b.HasIndex("KhoChuaId");

                    b.ToTable("KhoSanPham");
                });

            modelBuilder.Entity("DataContext.Entity.KhoVatTu", b =>
                {
                    b.Property<int>("VatTuId")
                        .HasColumnType("int");

                    b.Property<int>("KhoChuaId")
                        .HasColumnType("int");

                    b.Property<int>("SoLuongTon")
                        .HasColumnType("int");

                    b.HasKey("VatTuId", "KhoChuaId");

                    b.HasIndex("KhoChuaId");

                    b.ToTable("KhoVatTu");
                });

            modelBuilder.Entity("DataContext.Entity.LenhSX", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("BatDauSX")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreateBy")
                        .HasColumnType("int");

                    b.Property<int?>("DonHangId")
                        .HasColumnType("int");

                    b.Property<DateTime>("KetThucSX")
                        .HasColumnType("datetime2");

                    b.Property<int?>("KhoChuaId")
                        .HasColumnType("int");

                    b.Property<string>("MaLenhSX")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("SanPhamId")
                        .HasColumnType("int");

                    b.Property<int>("SoLuongSX")
                        .HasColumnType("int");

                    b.Property<int>("TrangThaiLenh")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdateAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UpdateBy")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MaLenhSX")
                        .IsUnique();

                    b.HasIndex("SanPhamId");

                    b.ToTable("LenhSanXuat");
                });

            modelBuilder.Entity("DataContext.Entity.NhaCungCap", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreateBy")
                        .HasColumnType("int");

                    b.Property<string>("DiaChi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaSoThue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sdt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenNCC")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("UpdateAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UpdateBy")
                        .HasColumnType("int");

                    b.Property<string>("hinhAnh")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("NhaCungCap");
                });

            modelBuilder.Entity("DataContext.Entity.NhanSu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ChucVu")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreateBy")
                        .HasColumnType("int");

                    b.Property<string>("DiaChi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GioiTinh")
                        .HasMaxLength(50)
                        .HasColumnType("int");

                    b.Property<string>("HinhAnh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoTenNhanSu")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("NguoiQuanLyId")
                        .HasColumnType("int");

                    b.Property<int>("PhongBan")
                        .HasColumnType("int");

                    b.Property<string>("Sdt")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TenDangNhap")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("UpdateAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UpdateBy")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TenDangNhap")
                        .IsUnique();

                    b.ToTable("NhanSu");
                });

            modelBuilder.Entity("DataContext.Entity.PhieuNhap", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreateBy")
                        .HasColumnType("int");

                    b.Property<string>("DiaChiNguon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DonNhapId")
                        .HasColumnType("int");

                    b.Property<int>("KhoChuaId")
                        .HasColumnType("int");

                    b.Property<int?>("LenhSanXuatId")
                        .HasColumnType("int");

                    b.Property<string>("MaPN")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("NgayNhap")
                        .HasColumnType("datetime2");

                    b.Property<int>("NhaCungCapId")
                        .HasColumnType("int");

                    b.Property<int>("SoLuongNhap")
                        .HasColumnType("int");

                    b.Property<double>("Thue")
                        .HasColumnType("float");

                    b.Property<double>("TienTruocThue")
                        .HasColumnType("float");

                    b.Property<double>("TongGiaTri")
                        .HasColumnType("float");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdateAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UpdateBy")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DonNhapId");

                    b.HasIndex("KhoChuaId");

                    b.ToTable("PhieuNhap");
                });

            modelBuilder.Entity("DataContext.Entity.PhieuXuat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreateBy")
                        .HasColumnType("int");

                    b.Property<string>("DiaChiDich")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DonHangId")
                        .HasColumnType("int");

                    b.Property<int>("KhachHangId")
                        .HasColumnType("int");

                    b.Property<int>("KhoChuaId")
                        .HasColumnType("int");

                    b.Property<string>("MaPX")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayXuatKho")
                        .HasColumnType("datetime2");

                    b.Property<int>("SoLuongXuat")
                        .HasColumnType("int");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdateAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UpdateBy")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DonHangId");

                    b.HasIndex("KhoChuaId");

                    b.ToTable("PhieuXuat");
                });

            modelBuilder.Entity("DataContext.Entity.PhuongThucThanhToan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreateBy")
                        .HasColumnType("int");

                    b.Property<int>("SoKyTra")
                        .HasColumnType("int");

                    b.Property<double>("SoPhanTramTraTruoc")
                        .HasColumnType("float");

                    b.Property<string>("TenDieuKhoan")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<double>("TienTraMoiKy")
                        .HasColumnType("float");

                    b.Property<DateTime>("UpdateAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UpdateBy")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("PhuongThucThanhToan");
                });

            modelBuilder.Entity("DataContext.Entity.SanPham", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreateBy")
                        .HasColumnType("int");

                    b.Property<int?>("DVTinhId")
                        .HasColumnType("int");

                    b.Property<double>("GiaBanSP")
                        .HasColumnType("float");

                    b.Property<double>("GiaGocSP")
                        .HasColumnType("float");

                    b.Property<int>("HanSanXuat")
                        .HasColumnType("int");

                    b.Property<string>("HinhAnh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("LoiNhuan")
                        .HasColumnType("float");

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SKU")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TenSP")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<double>("Thue")
                        .HasColumnType("float");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdateAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UpdateBy")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SKU")
                        .IsUnique();

                    b.ToTable("SanPham");
                });

            modelBuilder.Entity("DataContext.Entity.VatTu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreateBy")
                        .HasColumnType("int");

                    b.Property<int?>("DVTinhId")
                        .HasColumnType("int");

                    b.Property<double>("GiaBan")
                        .HasColumnType("float");

                    b.Property<string>("HinhAnh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mota")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenVatTu")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdateAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UpdateBy")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("VatTu");
                });

            modelBuilder.Entity("DataContext.Entity.VatTuCanDung", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("SanPhamId")
                        .HasColumnType("int");

                    b.Property<int>("SoLuongCan")
                        .HasColumnType("int");

                    b.Property<int?>("VatTuId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SanPhamId");

                    b.HasIndex("VatTuId");

                    b.ToTable("VatTuCanDung");
                });

            modelBuilder.Entity("DataContext.Entity.ChiTietCheTao", b =>
                {
                    b.HasOne("DataContext.Entity.LenhSX", "LenhSX")
                        .WithMany("chiTietCheTaos")
                        .HasForeignKey("LenhSXId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataContext.Entity.VatTu", "VatTu")
                        .WithMany("chiTietCheTaos")
                        .HasForeignKey("VatTuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LenhSX");

                    b.Navigation("VatTu");
                });

            modelBuilder.Entity("DataContext.Entity.ChiTietDonHang", b =>
                {
                    b.HasOne("DataContext.Entity.DonHang", "DonHang")
                        .WithMany("ChiTietDonHangs")
                        .HasForeignKey("DonHangId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataContext.Entity.SanPham", "SanPham")
                        .WithMany("ChiTietDonHangs")
                        .HasForeignKey("SanPhamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DonHang");

                    b.Navigation("SanPham");
                });

            modelBuilder.Entity("DataContext.Entity.ChiTietDonNhap", b =>
                {
                    b.HasOne("DataContext.Entity.DonNhap", "DonNhap")
                        .WithMany("ChiTietDonNhaps")
                        .HasForeignKey("DonNhapId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataContext.Entity.VatTu", "VatTu")
                        .WithMany()
                        .HasForeignKey("VatTuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DonNhap");

                    b.Navigation("VatTu");
                });

            modelBuilder.Entity("DataContext.Entity.ChiTietPhieuNhap", b =>
                {
                    b.HasOne("DataContext.Entity.PhieuNhap", "PhieuNhap")
                        .WithMany("ChiTietPhieuNhaps")
                        .HasForeignKey("PhieuNhapId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataContext.Entity.VatTu", "VatTu")
                        .WithMany("ChiTietPhieuNhaps")
                        .HasForeignKey("VatTuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PhieuNhap");

                    b.Navigation("VatTu");
                });

            modelBuilder.Entity("DataContext.Entity.ChiTietPhieuXuat", b =>
                {
                    b.HasOne("DataContext.Entity.PhieuXuat", "PhieuXuat")
                        .WithMany("ChiTietPhieuXuats")
                        .HasForeignKey("PhieuXuatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataContext.Entity.SanPham", "SanPham")
                        .WithMany("ChiTietPhieuXuats")
                        .HasForeignKey("SanPhamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PhieuXuat");

                    b.Navigation("SanPham");
                });

            modelBuilder.Entity("DataContext.Entity.DonHang", b =>
                {
                    b.HasOne("DataContext.Entity.KhachHang", "KhachHang")
                        .WithMany()
                        .HasForeignKey("KhachHangId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataContext.Entity.PhuongThucThanhToan", "PhuongThucThanhToan")
                        .WithMany("DonHangs")
                        .HasForeignKey("PhuongThucThanhToanId");

                    b.Navigation("KhachHang");

                    b.Navigation("PhuongThucThanhToan");
                });

            modelBuilder.Entity("DataContext.Entity.DonNhap", b =>
                {
                    b.HasOne("DataContext.Entity.NhaCungCap", null)
                        .WithMany("DonNhaps")
                        .HasForeignKey("NhaCungCapId");
                });

            modelBuilder.Entity("DataContext.Entity.KhoSanPham", b =>
                {
                    b.HasOne("DataContext.Entity.KhoChua", "KhoChua")
                        .WithMany("KhoSanPham")
                        .HasForeignKey("KhoChuaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataContext.Entity.SanPham", "SanPham")
                        .WithMany("KhoSanPhams")
                        .HasForeignKey("SanPhamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KhoChua");

                    b.Navigation("SanPham");
                });

            modelBuilder.Entity("DataContext.Entity.KhoVatTu", b =>
                {
                    b.HasOne("DataContext.Entity.KhoChua", "KhoChua")
                        .WithMany("KhoVatTus")
                        .HasForeignKey("KhoChuaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataContext.Entity.VatTu", "VatTu")
                        .WithMany()
                        .HasForeignKey("VatTuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KhoChua");

                    b.Navigation("VatTu");
                });

            modelBuilder.Entity("DataContext.Entity.LenhSX", b =>
                {
                    b.HasOne("DataContext.Entity.SanPham", "SanPham")
                        .WithMany()
                        .HasForeignKey("SanPhamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SanPham");
                });

            modelBuilder.Entity("DataContext.Entity.PhieuNhap", b =>
                {
                    b.HasOne("DataContext.Entity.DonNhap", "DonNhap")
                        .WithMany("PhieuNhaps")
                        .HasForeignKey("DonNhapId");

                    b.HasOne("DataContext.Entity.KhoChua", "KhoChua")
                        .WithMany("PhieuNhaps")
                        .HasForeignKey("KhoChuaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DonNhap");

                    b.Navigation("KhoChua");
                });

            modelBuilder.Entity("DataContext.Entity.PhieuXuat", b =>
                {
                    b.HasOne("DataContext.Entity.DonHang", "DonHang")
                        .WithMany("PhieuXuats")
                        .HasForeignKey("DonHangId");

                    b.HasOne("DataContext.Entity.KhoChua", "KhoChua")
                        .WithMany("PhieuXuats")
                        .HasForeignKey("KhoChuaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DonHang");

                    b.Navigation("KhoChua");
                });

            modelBuilder.Entity("DataContext.Entity.VatTuCanDung", b =>
                {
                    b.HasOne("DataContext.Entity.SanPham", "SanPham")
                        .WithMany("VatTuCanDungs")
                        .HasForeignKey("SanPhamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataContext.Entity.VatTu", "VatTu")
                        .WithMany()
                        .HasForeignKey("VatTuId");

                    b.Navigation("SanPham");

                    b.Navigation("VatTu");
                });

            modelBuilder.Entity("DataContext.Entity.DonHang", b =>
                {
                    b.Navigation("ChiTietDonHangs");

                    b.Navigation("PhieuXuats");
                });

            modelBuilder.Entity("DataContext.Entity.DonNhap", b =>
                {
                    b.Navigation("ChiTietDonNhaps");

                    b.Navigation("PhieuNhaps");
                });

            modelBuilder.Entity("DataContext.Entity.KhoChua", b =>
                {
                    b.Navigation("KhoSanPham");

                    b.Navigation("KhoVatTus");

                    b.Navigation("PhieuNhaps");

                    b.Navigation("PhieuXuats");
                });

            modelBuilder.Entity("DataContext.Entity.LenhSX", b =>
                {
                    b.Navigation("chiTietCheTaos");
                });

            modelBuilder.Entity("DataContext.Entity.NhaCungCap", b =>
                {
                    b.Navigation("DonNhaps");
                });

            modelBuilder.Entity("DataContext.Entity.PhieuNhap", b =>
                {
                    b.Navigation("ChiTietPhieuNhaps");
                });

            modelBuilder.Entity("DataContext.Entity.PhieuXuat", b =>
                {
                    b.Navigation("ChiTietPhieuXuats");
                });

            modelBuilder.Entity("DataContext.Entity.PhuongThucThanhToan", b =>
                {
                    b.Navigation("DonHangs");
                });

            modelBuilder.Entity("DataContext.Entity.SanPham", b =>
                {
                    b.Navigation("ChiTietDonHangs");

                    b.Navigation("ChiTietPhieuXuats");

                    b.Navigation("KhoSanPhams");

                    b.Navigation("VatTuCanDungs");
                });

            modelBuilder.Entity("DataContext.Entity.VatTu", b =>
                {
                    b.Navigation("ChiTietPhieuNhaps");

                    b.Navigation("chiTietCheTaos");
                });
#pragma warning restore 612, 618
        }
    }
}
